### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by mengstr** [atoone/BeastEm#1]
After installing SDL2 using `brew install sdl2 sdl2_gfx sdl2_ttf` and compiling it manually as 
```
g++ \
 -O3 -w -g -std=c++14 \
 *.cpp \
 src/*.cpp \
 -I/opt/homebrew/include/SDL2/ \
 -L/opt/homebrew/lib/ \
 -lSDL2 \
 -lSDL2_ttf \
 -lSDL2_gfx-1.0.0
```
I can run it, but it looks a bit wonky with two small frames stacked onto each other in a large window.  It was super long ago since I did anything myself with SDL but I could probably dig around a bit and see. Can you add a screenshot to the readme of how it is supposed to look like?

<img width="1800" alt="Microbeast2" src="https://user-images.githubusercontent.com/325326/235291891-b62482df-8ea2-4236-a721-9968a8fd4bd0.png">

**Comment by atoone** [comment]
Now resolved. Zoom feature added to support different display sizes and adjust for High DPI systems.
