### ISSUE TITLE
CPU issues

### ISSUE THREAD

**Issue by mengstr** [atoone/BeastEm#2]
Directly after starting the emulator, with the bios loaded, the CPU load is about 50% on a single core of an M1.  When the emulator clock is started, set to the default 8MHz, the core is pegged at 100%, the entire window get really sluggish (takes several seconds to mark keypresses on the softkeyboard). Then after a while the MacOS busy-indicator pinwheel of death is shown.

There must be some tight busy-polling loop going on in the code...

**Comment by atoone** [comment]
That's... interesting. I'll investigate.

**Comment by atoone** [comment]
It appears that the mktime call in the RTC (used to regularise time updates) is very expensive on Linux systems. Enabling the RTC in MicroBeast slowed down the emulator enormously.

The latest release removes that call and checks the time update by hand. Performance is now much better.

**Comment by mengstr** [comment]
Confirmed. 50% load on one core now, plus another 10% if the audio is enabled. Everything feels responsive and nice.
