### ISSUE TITLE
Potential audio issue on macOS

### ISSUE THREAD

**Issue by roscopeco** [atoone/BeastEm#7]
When built on macOS, I found that the emulator starts up emitting audio noise and cannot be stopped without exiting. 

I observed this behaviour on macOS Ventura, on both Intel and Apple Silicon Macs.

SDL 2 installed from Homebrew in both cases (for the appropriate arch). Versions below (from Intel, but my M1 environment is equivalent).

```
# cc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
```

```
# sdl2-config --version --cflags --libs
2.30.0
-I/usr/local/include/SDL2 -D_THREAD_SAFE
-L/usr/local/lib -lSDL2
```

**Comment by roscopeco** [comment]
N.B: no longer replicable on `gui-update` branch, potentially fixed?

**Comment by atoone** [comment]
New code appears to fix this problem. Will close shortly, unless any reports come in otherwise.

**Comment by roscopeco** [comment]
Agreed, I have been unable to replicate since the new code went in. Will close 👍
